# ------------------------------------
# SITE SETTINGS
# ------------------------------------
title: Open Address File
description: A campaign for open addresses in the UK.

# ------------------------------------
# GITHUB PAGES/JEKYLL CONFIGURATION
# ------------------------------------

github_repo_url: "https://github.com/regulate-tech/openaddressfile" 
github_repo: regulate-tech/openaddressfile
# BASEURL: Must match the repository name for Project Pages
# This ensures that internal links start with /openaddressfile/
baseurl: "/openaddressfile"
# URL: This is the host URL. Use your actual GitHub username/organization.
url: "https://regulate-tech.github.io"
# URL settings for GitHub Pages live
# baseurl: ""  # Empty for custom domain
# url: "https://openaddressfile.uk"

# THEME: Use a theme supported by GitHub Pages
theme: jekyll-theme-minimal
# STRUCTURE: Put each .md file into a subdir with the same name
permalink: pretty

# ------------------------------------
# JEKYLL BUILD SETTINGS (For Local Testing)
# ------------------------------------
# Exclude the vendor folder where local gems are installed
exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock

# Hide GitHub repository information
github_username: # leave blank
repository: # leave blank
show_downloads: false
github:
  is_project_page: false
  is_user_page: false

# Disable repository link
public: false
